config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users

  resources :sites
  # get '/user/', to: 'users#show', as: 'user'

  resources :users do
    resources :sites
  end

    get 'error' => 'sites#error'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  validates :link, :presence => true
end


# https://guides.rubyonrails.org/v3.2.13/active_record_validations_callbacks.html#presence

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  ### Error page, redirected to when Server Error
  def error
      @user = current_user
      @sites = Site.where(user_id: @user).order("created_at ASC")
  end

  # GET /sites
  # GET /sites.json
  def index

    @user = current_user
    @sites = Site.where(user_id: @user).order("created_at DESC")

    ### Necessary to require for Heroku for view or WILL error out
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    begin
      @sites.each do |site|

        @site_link = site.link.to_s

        if @site_link.exclude? "http"
            redirect_to error_path and return
        end

        @site_open = Nokogiri::HTML(open(@site_link))
        @official_title = @site_open.at_css("title").text

        ### Rescues from OpenURI HTTPError(s)
        rescue OpenURI::HTTPError
          ###(Specifically wrote rescue block from begin for 900 Server error when trying to scrape LinkedIn Profiles)
        redirect_to error_path and return
      end
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    ### Necessary to require for Heroku for view or WILL error out
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    @user = current_user
    @site = Site.find(params[:id])
    @site_link = @site.link.to_s

    if @site_link.exclude? "http"
        redirect_to error_path and return
    end

    begin
      # @site_link = @site.link.to_s
      @site_element = @site.element

      @html_doc = Nokogiri::HTML(open(@site_link))
      @official_title = @html_doc.at_css("title").text
      @element_results = @html_doc.search("#{@site.element}")
      ### Rescues from OpenURI HTTPError(s)
      rescue OpenURI::HTTPError

      redirect_to error_path and return
    end
  end

  # GET /sites/new
  def new
    @user = current_user
    @site = @user.sites.build
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = current_user.sites.build(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:link, :title, :element, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :checkyoself

  def index
    # => #redering places#index
    @user = current_user
    @sites = Site.where(user_id: @user).order("created_at DESC")
  end

  def edit
  end

  def show
    # => #redering places#index
    @user = current_user
    @sites = Site.where(user_id: @user).order("created_at DESC")
  end

private
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation )
  end

  # def checkyoself
  #   redirect_to(root_url) unless current_user
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Element Scraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--import bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  </head>

      <div class="header">
          <div class="top-header">
              <nav class="navbar navbar-expand-lg navbar-light bg-faded">
                <a class="navbar-brand" href="/">Element Scraper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

                  <div class="navbar-nav">

                    <% if user_signed_in?  %>

                      <%= link_to "Hello #{current_user.email}", user_sites_path(current_user), class:"nav-item nav-link" %>

                      <%=link_to 'My Profile', user_sites_path(current_user), class:"nav-item nav-link" %>

                      <!-- <%=link_to 'Add Site', new_user_site_path(current_user), class:"nav-item nav-link"  %> -->

                      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-item nav-link" %>

                    <% else  %>

                    <%= link_to 'Home', root_url, class:"nav-item nav-link" %>
                    <%= link_to 'Login', new_user_session_path, class:"nav-item nav-link" %>
                    <%= link_to 'Sign Up', new_user_registration_path, class:"nav-item nav-link" %>
                    <% end %>

                  </div>
                </div>
              </nav>
          </div>
        </div>

  <body>
    <div class="container py-5 text-center">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<main role="main" class="container">

  <% if user_signed_in?  %>
    <h1> <%= link_to "Welcome #{current_user.email}", user_sites_path(current_user) %></h1>
  <% end %>

  <div class="jumbotron">
    <h1>Element Scraper</h1>

    <p class="lead"> This Application is a Web Scraping tool created to help you better examine the elements that make up your favorite webpages. Keep in mind not all pages support web scraping, so please, respect the rules of the domain owners. </p>

    <% if current_user == nil  %>

    <div class="btn-group">
      <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-success btn-lg " %>
      <%= link_to 'Login', new_user_session_path, class:"btn btn-primary btn-lg " %>
    </div>

      <br>
      <p> <h5>Feel free to explore our application with our sample account </h5>
        <strong> e-mail:</strong> sample@example.com
        <br>
        <strong> password: </strong> sampleaccount
      </p>
    <% end %>

  </div>
</main>

app/views/sites/_form.html.erb
<hr>
<%= form_with(model: @site, local: true) do |form| %>

  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div>
    <%= "User ID" %>
    <br>
    <%= current_user.id %>
    <br>
    <% form.label :user_id %>
    <% form.text_area :user_id, id: :current_user_id %>
  </div> -->

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :site_link %>
  </div>

  <div class="field">
    <%= form.label :element, "Select Element:" %>
    <%= form.select :element, [ 'html', 'header', 'head','style', 'article', 'section', 'hgroup', 'title', 'footer',  'meta', 'link', 'nav', 'body', 'script',  'var', 'source', 'div', 'p', 'table', 'tbody', 'thead', 'tr', 'td', 'th', 'form', 'table', 'label', 'select', 'option', 'a', 'ul', 'li', 'ol',  'img','h1', 'h2', 'h3', 'h4', 'h5', 'h6',  'br', 'hr',  'blockquote', 'main'].sort, id: :site_element %> element
  </div>

  <hr>
    <h4>Optional Title </h4>
    <div class="field">
      <%= form.label :title, 'Your Title:' %>
      <%= form.text_field :title, id: :site_title %>
    </div>
  <hr>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>


<%= link_to 'Delete', @site, method: :delete, data: { confirm: 'Are you sure you want to remove this site from your list?' }, class:"btn btn-danger" %>

<br>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/error.html.erb
<h1>Scraping Error</h1>

<% if @sites.last.link.exclude? "http" %>
  <h2>Site must include "http" or "https" in link field.
  <br> <small> (See link of this site in address bar for example)</small>
</h2>
<br>

<% else %>
  <h2>Last site added does not allow scraping.</h2>
<% end %>

<%= link_to 'Press Here To Remove Site From List', @sites.last, method: :delete, class:"btn btn-lg btn-outline-primary" %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<br>

  <%= link_to 'New Site', new_user_site_path(current_user), class:"btn btn-primary btn-block btn-lg" %>

<br>
<hr>

<!-- Must leave this each loop from controller or breaks -->
    <% @sites.each do |site| %>
    <% @site_link = site.link.to_s %>
    <% @site_open = Nokogiri::HTML(open(@site_link)) %>
    <% @official_title = @site_open.at_css("title").text %>

      <!-- Gets Scraped Site title -->
      <h5> Title:
        <% if site.title.blank? && @official_title.blank? %>
          <%= link_to "No Title Availble", site  %>
        <% elsif @official_title.blank?  %>
           <%= link_to "#{site.title}", site  %>
       <% elsif site.title.blank? %>
           <%= link_to "#{@official_title}", site  %>
       <% else %>
       <%= link_to "No Title Availble", site  %>
        <% end %>   <!-- End of elsif -->
      </h5>
      
      <!-- Gets site link -->
      <h6>
        Link: <a href="<%= site.link %>" target="_blank"> <%= site.link[8..40] %>......</a>
      </h6>
          <%= link_to 'Show', site %>  |
          <%= link_to 'Edit', edit_site_path(site) %> |
          <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %>
<hr>
    <% end %> <!-- End of do loop -->

<br>

<%= link_to "Back", :back, class:"btn btn-outline-primary"%>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<!-- <font style="color:green;">
  <p id="notice"><%= notice %></p>
</font> -->

<h1> Page </h1>

<% if @site.title.blank? && @official_title.blank? %>
  <h5>
      Title: <a href="<%= @site.link %>" target="_blank">
        No Title Availble
      </a>
  </h5>
<% elsif @official_title.blank?  %>
    <h5>
        Title: <a href="<%= @site.link %>" target="_blank">
          <%= "#{@site.title}"%>
        </a>
    </h5>
<% elsif @site.title.blank?  %>
    <h5>
        Title: <a href="<%= @site.link %>" target="_blank">
          <%= "#{@official_title}"%>
        </a>
    </h5>
<% else %>
    <h5>
        Title: <a href="<%= @site.link %>" target="_blank">
          No Title Availble
        </a>
    </h5>
<% end %>

<h6>
  <p>
    <strong>Link:</strong>
    <a href="<%= @site.link %>" target="_blank"> <%= @site.link %></a>
  </p>
</h6>

<hr>

<% if @site.element.empty? != true %>
  <h6>
    <p>
      <strong>Selected Element:</strong>
      <%= @site.element %>
      <br>

      <strong>Number of Element Results:</strong>
      <%= @element_results.to_a.count %>

      <br>
      <br>

      <%= link_to 'Edit Selected Element', edit_site_path(@site), class:"btn btn-outline-secondary" %>

      <br>
      <hr>

      <% if @element_results.to_a.count < 1 %>
        <h1>
          <font style="color:red;">  The <%= @site.element %> element is not used on your Webpage </font>
        </h1>
      <% else  %>

        <% element_counter = 0 %>
        <% length = @element_results.length.to_i %>

        <% @element_results.each do |element| %>
          <strong> Element Result: <%= element_counter += 1%> </strong>

          <br>

          <%= element %>

          <hr>
          
        <% end %>
      <% end  %>
    </p>
  </h6>
<% end %>

<br>

<%= link_to "Back", :back, class:"btn btn-outline-primary"%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>User#Show</h1>
User Profile